### ISSUE TITLE
NRPE check reports OK although there are errors

### ISSUE THREAD

**Issue by marcusboden** [canonical/charm-juju-backup-all#55]
We have an issue where part of the backup fails, but the NRPE doesn't notice it and happily returns "OK". The problem is, that the code [looks for the `ERROR` key in the output json](https://github.com/canonical/charm-juju-backup-all/blame/5ad014f09978f7543f2c5f85385b0c722bb0f0da/scripts/plugins/check_auto_backup_results.py#L111), however, this is what we got:
```
$ cat /var/lib/jujubackupall/auto_backup_results.json
{
[... working backups ...]
  "errors": [
    {
      "controller": "foundations-maas",
      "model": "openstack",
      "app": "mysql-innodb-cluster",
      "charm": "mysql-innodb-cluster",
      "error_reason": "JujuTimeoutError: Task 'mysqldump' timed out (timeout=1800)."
    }
  ]
}
```
I wonder where this change comes from? juju? Anyway, should be an easy fix

**Comment by samuelallan72** [comment]
@marcusboden was this working as expected in the past (as in, did results with partial errors as in your example get picked up by NRPE)? Because I read through the code and it seems this behaviour hasn't changed since December 2021.

What should the expected behaviour be? I'm guessing it should be a critical failure even if a single backup failed?

Technical info:
- The output json is written to file from auto_backup.py in this repo.
  - The json is generated by the [juju-backup-all backup process](https://github.com/canonical/juju-backup-all/blob/3bd5b78a0d8841f504714d8a7ef1fda95b1774f2/jujubackupall/backup.py#L305-L307), including the `errors` key.
  - However, the output with the `ERROR` key is written directly by [auto_backup.py](https://github.com/canonical/charm-juju-backup-all/blob/4dffe675298bcb78ff22e3d17b4c5135107d0542/scripts/templates/auto_backup.py#L236-L238) in this repo, if the juju-backup-all backup process raises an exception.
- This does not appear to be new behaviour, at least not since december 2021.

**Comment by marcusboden** [comment]
We may have missed that since 2021, to be honest. Thankfully, we only need the mysql backups in the worst case scenario, so it did not have any impact so far.
But seeing that we essentially missed this for quite some time, I think we should have this go full CRITICAL. It's a backup failure in a backup charm, so essentially the charm doesn't work anymore at that point.
